sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 744669
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tFRwUwgAwiHa9VadjxM
    access-key-secret: 2uiG9LfBfKAf2s2tRfOOOoBoFBxVmY
    bucket-name: gulinall-hkw